### ISSUE TITLE
Secure Storage of Sensitive Variables and Keys

### ISSUE THREAD

**Issue by SverreNystad** [CogitoNTNU/PropagandaAI#6]
As PropagandaAI will utilize several sensitive variables and keys, it's crucial to ensure they are securely stored and absent from the commit history from the project's inception.

**Possible solution:**
* Create a file called `.env` in the root of the project. This file should contain the following:
   * API_KEY: The API key for the OpenAI API.
   * DB configuration
* Develop a configuration file/script to extract values from the .env file
NOTE: Never Commit .env to Version Control. The .env file should be kept private and never be committed to the project as it contains secrets like API keys.

**Acceptance criteria:**
* Identify all sensitive data that needs to be stored in the .env file.
* Implement a mechanism within the application to securely access these secrets.

**Comment by Knolaisen** [comment]
This is solved on Main
